### ISSUE TITLE
Xfce inactive desktop icons have solid light gray background.

### ISSUE THREAD

**Issue by regs01** [daniruiz/skeuos-gtk#50]
That's because in the beginning there is explicit `.view:backdrops`
https://github.com/daniruiz/skeuos-gtk/blob/095e06aa44c637af675850e421057c6f09b9f8d0/src/sass/gtk3/upstream/_common.scss#L113

Which is not being cancelled for `XfdesktopIconView.view`
https://github.com/daniruiz/skeuos-gtk/blob/095e06aa44c637af675850e421057c6f09b9f8d0/src/sass/gtk3/_applications.scss#L192

Adding `XfdesktopIconView.view:backdrops` would fix it.

```scss
XfdesktopIconView.view,
XfdesktopIconView.view:backdrops {
  background-color: transparent;
  color: white;
  text-shadow: 0 1px 2px black;
}
```

![Screenshot_2024-10-19_15-34-47_cut](https://github.com/user-attachments/assets/aaaab705-8d03-49c5-8769-505649b090d3)
